### 5.2 온기 우편함 조회
// @no-log
GET {{host_url}}/api/v1/onjungs/events/overviews?
    page={{event.API_5_2.page}}&
    size={{event.API_5_2.size}}
Authorization: Bearer {{access_token}}

### 5.3 나의 식권 조회
// @no-log
GET {{host_url}}/api/v1/tickets?
    page={{event.API_5_3.page}}&
    size={{event.API_5_3.size}}
Authorization: Bearer {{access_token}}

### 5.4 식권 QR코드 조회하기
// @no-log
GET {{host_url}}/api/v1/tickets/{{event.API_5_4.id}}/briefs
Authorization: Bearer {{access_token}}

### 5.5 식권 사용하기
// @no-log
POST {{host_url}}/api/v1/tickets/validate
Content-Type: application/json

{
  "hashed_ticket_id": "{{event.API_5_5.hashed_ticket_id}}",
  "password": "{{event.API_5_5.password}}"
}

### 5.6 보유한 티켓 수 조회하기
// @no-log
GET {{host_url}}/api/v1/users/tickets/count
Authorization: Bearer {{access_token}}
