### 6.1 게시글 리스트 조회
// @no-log
GET {{host_url}}/api/v1/boards/overviews?
    page={{suggestion.API_6_1.page}}&
    size={{suggestion.API_6_1.size}}
Authorization: Bearer {{access_token}}

### 6.2 게시글 상세 정보 조회
// @no-log
GET {{host_url}}/api/v1/boards/{{suggestion.API_6_2.id}}/details
Authorization: Bearer {{access_token}}

### 6.3 댓글 조회
// @no-log
GET {{host_url}}/api/v1/boards/{{suggestion.API_6_3.id}}/comments/overviews?
    page={{suggestion.API_6_3.page}}&
    size={{suggestion.API_6_3.size}}
Authorization: Bearer {{access_token}}

### 6.4 게시글 등록하기
// @no-log
POST {{host_url}}/api/v1/boards
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{access_token}}

--boundary
Content-Disposition: form-data; name="body"
Content-Type: application/json

    {
        "title": "{{suggestion.API_6_4.title}}",
        "content": "{{suggestion.API_6_4.content}}"
    }

--boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< /Users/kyeom/Desktop/1_banner.png

### 6.5 댓글 등록하기
// @no-log
POST {{host_url}}/api/v1/boards/{{suggestion.API_6_5.id}}/comments
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "content": "{{suggestion.API_6_5.content}}"
}