global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['127.0.0.1:8080']

  - job_name: 'bank'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['127.0.0.1:8081']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jmeter'
    static_configs:
      - targets: ['127.0.0.1:9270']  # JMeter 플러그인을 통한 데이터 수집