### 테스트용 슈퍼유저 로그인
// @no-log
POST {{host_url}}/api/v1/auth/login
Content-Type: application/x-www-form-urlencoded

serial_id={{auth.API_LOGIN_SUPER_USER.serial_id}}&
password={{auth.API_LOGIN_SUPER_USER.password}}

> {%
    client.global.set("access_token", response.body.data.access_token);
    client.global.set("refresh_token", response.body.data.refresh_token);
%}

### 1.1 사용자 로그인 (Kakao Oauth)
// @no-log
POST {{host_url}}/api/v1/oauth/login
Content-Type: application/json

{
  "access_token": "{{auth.API_1_1_KAKAO.access_token}}",
   "provider": "kakao"
}

> {%
    client.global.set("access_token", response.body.data.access_token);
    client.global.set("refresh_token", response.body.data.refresh_token);
%}

### 1.2 디바이스 토큰 갱신
// @no-log
PATCH {{host_url}}/api/v1/auth/device-token
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "device_token": "{{auth.API_1_2.device_token}}"
}

### 1.3 JWT 재발급
// @no-log
POST {{host_url}}/api/v1/auth/reissue/token
Authorization: Bearer {{refresh_token}}

### 1.4 사용자 로그아웃
// @no-log
POST {{host_url}}/api/v1/auth/logout
Authorization: Bearer {{access_token}}

### 2.1 가게 일반 회원가입 (데이터 삽입용)
// @no-log
POST {{host_url}}/api/v1/auth/sign-up
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="logo"; filename="image.png"
Content-Type: image/png

< /Users/kyeom/Desktop/image1.png

--boundary
Content-Disposition: form-data; name="banner"; filename="image.png"
Content-Type: image/png

< /Users/kyeom/Desktop/image2.png

--boundary
Content-Disposition: form-data; name="body"
Content-Type: application/json

{
	"serial_id" : "{{auth.API_2_1.serial_id}}",
	"password" : "{{auth.API_2_1.password}}",
	"store_info" :
	{
		"onjung_tag" : ["{{auth.API_2_1.store_info.onjung_tag[0]}}", "{{auth.API_2_1.store_info.onjung_tag[1]}}"],
		"title" : "{{auth.API_2_1.store_info.title}}",
		"youtube_url" : "{{auth.API_2_1.store_info.youtube_url}}",
		"name" : "{{auth.API_2_1.store_info.name}}",
		"category" : "{{auth.API_2_1.store_info.category}}",
		"introduction" : "{{auth.API_2_1.store_info.introduction}}"
	},
	"ocr_info" :
	{
		"store_name" : "{{auth.API_2_1.ocr_info.store_name}}",
		"address_name" : "{{auth.API_2_1.ocr_info.address_name}}"
	},
	"bank_info" :
	{
		"name": "{{auth.API_2_1.bank_info.name}}",
		"account_number" : "{{auth.API_2_1.bank_info.account_number}}"
	}
}

### 2.2 탈퇴하기
// @no-log
DELETE {{host_url}}/api/v1/auth
Authorization: Bearer {{access_token}}