### 4.1 전체 온기 통계 조회
// @no-log
GET {{host_url}}/api/v1/onjungs/summaries
Authorization: Bearer {{access_token}}

### 4.2 후원 횟수 조회
// @no-log
GET {{host_url}}/api/v1/onjungs/count
Authorization: Bearer {{access_token}}

### 4.3 온기 간단 정보 조회
// @no-log
GET {{host_url}}/api/v1/onjungs/briefs
Authorization: Bearer {{access_token}}

### 4.4 가게 방문 인증용 영수증 OCR 조회하기
// @no-log
POST {{host_url}}/api/v1/receipts/ocr
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="receipt.jpg"
Content-Type: image/jpeg

< /Users/kyeom/Desktop/receipt3.jpeg

### 4.5 영수증 리뷰 등록하기
// @no-log
POST {{host_url}}/api/v1/receipts
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "store_name": "{{onjung.API_4_5.store_name}}",
  "store_address": "{{onjung.API_4_5.store_address}}",
  "payment_date": "{{onjung.API_4_5.payment_date}}",
  "payment_amount": "{{onjung.API_4_5.payment_amount}}"
}

### 4.6 온기 공유하기
// @no-log
PUT {{host_url}}/api/v1/stores/{{onjung.API_4_6.id}}/shares
Authorization: Bearer {{access_token}}

### 4.7 가게 후원 동참하기
// @no-log
POST {{host_url}}/api/v1/stores/{{onjung.API_4_7.id}}/donations
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "event_id": {{onjung.API_4_7.event_id}},
  "donation_amount": {{onjung.API_4_7.donation_amount}}
}
